openapi: "3.0.0"
info:
  version: 1.0.0
  title: Google Sheet Query API phase1
  description: >
    This API retrieves product descriptions based on serial
  license:
    name: MIT
servers:
  - url: https://script.google.com/macros/s/AKfycbzE51wwks7-weeqHOwH1pgJC7C0Dk7B7FE3XF3-0Vxf4xMxl7lPDYQx0QwodXgfoEh6
paths:
  /exec:
    get:
      summary: Retrieve product details based on product serial
      operationId: findProductsByCode
      parameters:
      - in: query
        name: query
        schema:
          type: string
          minLength : 3
        required: true
        description: Serial to look up products. Performs partial match.
      responses:
        '200':
          description: Found products
          content:
            application/json:
              schema:
                type: object
                properties :
                  total:
                    type: number
                    description : Total number of that match the provided serial
                  entries:
                    type: array
                    items:
                      type: object
                      properties:
                        serial:
                          type: string
                          example: "11242001"
                        model:
                          type: string
                          example: "ss1123400"
                        sku:
                          type: string
                          example : "SPA/FILTER"
                        description:
                          type: string
                          example: "Replacement Filter Cartridge"
                        url:
                          type: string
                          example: "https://shop.strongspas.com/shop/parts/filters"
        '400':
          description: Missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                example:
                  status: error
                  message: Missing parameters
